name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"        # v0.1.0, v1.2.3, etc.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for trusted publishing
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Build sdist & wheel
      run: |
        python -m pip install --upgrade pip build
        python -m build --sdist --wheel --outdir dist

    - name: Publish to PyPI (trusted)
      uses: pypa/gh-action-pypi-publish@v1
      with:
        skip-existing: true
